INSERT INTO countries(name) VALUES('АВСТРАЛИЯ')
INSERT INTO countries(name) VALUES('АВСТРИЯ')
INSERT INTO countries(name) VALUES('АЛБАНИЯ')
INSERT INTO countries(name) VALUES('АЗЕРБАЙДЖАН')
INSERT INTO countries(name) VALUES('АЛЖИР')
INSERT INTO countries(name) VALUES('АНГОЛА')
INSERT INTO countries(name) VALUES('АНДОРРА')
INSERT INTO countries(name) VALUES('АНТИГУА')
INSERT INTO countries(name) VALUES('АРГЕНТИНА')
INSERT INTO countries(name)VALUES('АРМЕНИЯ')