INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('Папа Оскара', 5, 9, 8, 1)
INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('Волшебник', 3, 8, 9, 1)
INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('Старший сын мельника', 5, 9, 8, 1)
INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('Тетушка Мэлкин', 1, 1, 1, 3)
INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('Король', 3, 8, 9,  3)
INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('Эдвард', 5, 9, 8, 5)
INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('Люси', 21, 1, 3, 6)
INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('Абилин', 19, 3, 5, 8)
INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('Пелегрина', 17,  5, 7, 8)
INSERT INTO roles(name, characteristic_id, actor_id, understudy_id, performance_is) VALUES('МАСА', 15, 5, 7, 9)