INSERT INTO toureProducer(toure_id, producer_id ) VALUES(0, 0)
INSERT INTO toureProducer(toure_id, producer_id ) VALUES(1, 1)
INSERT INTO toureProducer(toure_id, producer_id ) VALUES(2, 2)
INSERT INTO toureProducer(toure_id, producer_id ) VALUES(3, 3)
INSERT INTO toureProducer(toure_id, producer_id ) VALUES(4, 4)