INSERT INTO user_roles(name) VALUES('Работник отдела кадров')
INSERT INTO user_roles(name) VALUES('Менеджер расписания')
INSERT INTO user_roles(name) VALUES('Постановщик')
INSERT INTO user_roles(name) VALUES('Составитель брошюр')
INSERT INTO user_roles(name) VALUES('Директор')