INSERT INTO workers(name, characteristic_id) VALUES('Снигирь Юлия', 12)
INSERT INTO workers(name, characteristic_id) VALUES('Чулпан Хаматова', 1)
INSERT INTO workers(name, characteristic_id) VALUES('Евгения Уралова', 14)
INSERT INTO workers(name, characteristic_id) VALUES('Александра Родина', 3)
INSERT INTO workers(name, characteristic_id) VALUES('Юлия Пересильд', 16)
INSERT INTO workers(name, characteristic_id) VALUES('Маврина Юлия', 5)
INSERT INTO workers(name, characteristic_id) VALUES('Медина Ольга', 18)
INSERT INTO workers(name, characteristic_id) VALUES('Андоленко Карина', 7)
INSERT INTO workers(name, characteristic_id) VALUES('Александр Романцов', 19)
INSERT INTO workers(name, characteristic_id) VALUES('Валерий Кузин', 21)
INSERT INTO workers(name, characteristic_id) VALUES('Абряров Шамиль', 11)
INSERT INTO workers(name, characteristic_id) VALUES('Анастасия', 14)
INSERT INTO workers(name, characteristic_id) VALUES('Анчаров Михаил', 15)
INSERT INTO workers(name, characteristic_id) VALUES('Добржанская Любовь', 16)
INSERT INTO workers(name, characteristic_id) VALUES('Дольский Александр', 17)
INSERT INTO workers(name, characteristic_id) VALUES('Дягилева Янка', 18)
INSERT INTO workers(name, characteristic_id) VALUES('Есипов Борис', 19)
INSERT INTO workers(name, characteristic_id) VALUES('Захарченко Любовь', 20)
INSERT INTO workers(name, characteristic_id) VALUES('Зыков Юрий', 21)
INSERT INTO workers(name, characteristic_id) VALUES('Игнатова Елена', 22)
INSERT INTO workers(name, characteristic_id) VALUES('ПОЛ ТОМАС АНДЕРСОН', 23)
INSERT INTO workers(name, characteristic_id) VALUES('МАЙЯ АНЖЕЛУ', 24)
INSERT INTO workers(name, characteristic_id) VALUES('ДАНИЭЛ АНКЕР', 25)
INSERT INTO workers(name, characteristic_id) VALUES('КЕЙТ БАРКЕР-ФРЕЙЛАНД', 26)
INSERT INTO workers(name, characteristic_id) VALUES('ПЭРИС БАРКЛЭЙ', 27)
INSERT INTO workers(name, characteristic_id) VALUES('ТРОЙЭН БЕЛЛИСАРИО', 27)
INSERT INTO workers(name, characteristic_id) VALUES('ДЖЕК БЕНДЕР', 28)
INSERT INTO workers(name, characteristic_id) VALUES('АНДРЕА БЕРЛОФФ', 2)
INSERT INTO workers(name, characteristic_id) VALUES('ЭДВАРД БЕРНС', 2)
INSERT INTO workers(name, characteristic_id) VALUES('КЭТРИН БИГЕЛОУ', 3)
INSERT INTO workers(name, characteristic_id) VALUES('СЕРГЕЙ АЙНУТДИНОВ', 4)
INSERT INTO workers(name, characteristic_id) VALUES('ИРИНА АКИМОВА', 5)
INSERT INTO workers(name, characteristic_id) VALUES('АЛЕКСЕЙ АКСЁНОВ', 6)
INSERT INTO workers(name, characteristic_id) VALUES('АВДОТЬЯ АЛЕКСАНДРОВА', 7)
INSERT INTO workers(name, characteristic_id) VALUES('РОМАН АЛЕКСАШЕВ', 8)
INSERT INTO workers(name, characteristic_id) VALUES('ИРИНА АЛЕКСЕЕВА', 9)
INSERT INTO workers(name, characteristic_id) VALUES('СЕРГЕЙ АЛИБЕКОВ', 10)
INSERT INTO workers(name, characteristic_id) VALUES('ЕЛЕНА АМШИНСКАЯ', 11)
INSERT INTO workers(name, characteristic_id) VALUES('РОМАН АНИСИМОВ', 12)
INSERT INTO workers(name, characteristic_id) VALUES('АЛЕКСАНДРА АНТОНОВА', 13)
INSERT INTO workers(name, characteristic_id) VALUES('Карлос Клайбер', 15)
INSERT INTO workers(name, characteristic_id) VALUES('Абдурахманова Дильбар Гулямовна', 16)
INSERT INTO workers(name, characteristic_id) VALUES('Клаудио Аббадо', 17)
INSERT INTO workers(name, characteristic_id) VALUES('Аим Эммануэль', 19)
INSERT INTO workers(name, characteristic_id) VALUES('Леонард Бернстайн', 21)
INSERT INTO workers(name, characteristic_id) VALUES('Белинфанте Фрида', 22)
INSERT INTO workers(name, characteristic_id) VALUES('Герберт фон Караян', 23)
INSERT INTO workers(name, characteristic_id) VALUES('Бройнинг-Сторм Гунна', 24)
INSERT INTO workers(name, characteristic_id) VALUES('Николаус Арнонкур ', 25)
INSERT INTO workers(name, characteristic_id) VALUES('Буланже Надя', 26)